print('Введите плей-лист папы:')
first_song=input()
second_song=input()
third_song=input()
fourth_song=input()
fifth_song=input()
print('Плей-лист мамы:')
print(fifth_song)
print(fourth_song)
print(third_song)
print(second_song)
print(first_song)